name: Delete old m3u files (7 days)

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete old .m3u files
        run: |
          git ls-files "*.m3u" | while read file; do
            commit_date=$(git log -1 --format="%ct" -- "$file")
            now=$(date +%s)
            diff=$(( (now - commit_date) / 86400 ))

            echo "$file is $diff days old"

            if [ "$diff" -ge 7 ]; then
              echo "Deleting $file"
              rm -f "$file"
            fi
          done

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add -A
          git commit -m "Auto delete .m3u older than 7 days" || echo "No changes"
          git push
